-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 110, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1807 s <<< FAILURE! -- in TestSuite
TestNGTestRunner.runScenario["View api is failed", "Order confirmation Page error handling"](68) -- Time elapsed: 38.16 s <<< FAILURE!
java.lang.AssertionError: expected [https://rahulshettyacademy.com/client/dashboard/order-details/67763d3de2b5443b1f0e1aa1] but found [https://rahulshettyacademy.com/client/dashboard/order-details/67763cf2e2b5443b1f0e19f8]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:656)
	at org.testng.Assert.assertEquals(Assert.java:666)
	at StepDefinitions.UITest.OrdersPage.ErrorHandlingStepDefImpl.isDisplayedAndErrorOccurs(ErrorHandlingStepDefImpl.java:158)
	at âœ½."You are not authorize to view this order" is displayed and "Unknown error occured" Error occurs(file:///C:/Users/santh/Desktop/Ecommerce%20Automation/Selenium/EcommercePractise/src/test/java/FeatureFiles/UITest/OrdersPage/ErrorHandling.feature:18)

